spring.application.name=auth-service

spring.datasource.url=jdbc:oracle:thin:@${URI_DB:oracle-auth-db}:1521/XEPDB1
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# JWT config
jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER}